### ISSUE TITLE
レポジトリについて

### ISSUE THREAD

**Issue by rkun123** [yurupro/MesistantDevice#1]
[yurupro/mesistant](../../Mesistant)がサーバーなので、まあその中に`/public`でも作ってそこでフロントエンドを作ってもらうという形でも いいかなって思ってるんですがいかが？
そのほうがお互いの進捗とかi見やすいし。
どうせサーバー側でホスティングするつもりだし。

**Comment by Prokuma** [comment]
サーバとウェブのフロントエンドは同じレポジトリでいいと思うけど、レポジトリはハードウェアのためのものだから分離した

**Comment by rkun123** [comment]
なるほど。では こっちはClientuというよりはDevicenとかにしたほうがいいかも

**Comment by Prokuma** [comment]
そっちのほうが良さそうだね
変更する
